version: '3'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  app:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./app:/src/app
      - ./nodemon.json:/src/nodemon.json
    container_name: app
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: node build/index.js